---
title: "data_import"
output: html_document

```{r}
library(tidyverse)
```

```{r}
litters_df = 
  read_csv(file = "./data/FAS_litters.csv")
```

```{r}
names(litters_df)
```

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

```{r}
litters_df
```

```{r}
skimr::skim(litters_df)
```

```{r}
litters_df = 
    read_csv(file = "./data/FAS_litters.csv",
        na = c(".", "NA", ""),
    col_types = cols(
      Group = col_character(),
      `Litter Number` = col_character(),
      `GD0 weight` = col_double(),
      `GD18 weight` = col_double(),
      `GD of Birth` = col_integer(),
      `Pups born alive` = col_integer(),
      `Pups dead @ birth` = col_integer(),
      `Pups survive` = col_integer()
    )
  )
tail(litters_df)
```

## import pups data
```{r}
pups_df = 
  read_csv(
    "./data/FAS_pups.csv",
    skip = 3,
    na=c("NA", ".", "")
  )
  
pups_df =
  janitor::clean_names(pups_df)
```

### excel
```{r}
library(readxl)
mlb_df =
  read_excel("./data/mlb11.xlsx", n_max = 20)
  head(mlb_df, 5)
```

```{r}
fotr_df =
  read_excel("data/LotR_Words.xlsx", range = "B3:B6")
```

```{r}
library(haven)
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
head(pulse_df, 5)
```

```{r}
litters_df_base =
  read.csv("data/FAS_litters.csv")
```

```{r}
pups_df_base = read.csv("./data/FAS_litters.csv")
```

```{r}
library(readr)
pups_df = read_csv("./data/FAS_litters.csv")
```

```{r}
class(pups_df_base)
class(pups_df)
```


```{r}
print(pups_df_base)
print(pups_df)
```

```{r}
library(janitor)
pups_df = clean_names(pups_df)
pups_df$Sex
pups_df$sex
```
